### ISSUE TITLE
多曝光图像融合数据集的划分问题

### ISSUE THREAD

**Issue by WinniePooh-XI** [Linfeng-Tang/SwinFusion#26]
每个文件夹中有多张曝光图像，该如何选取过曝光和欠曝光图像呢？
如果方便的话，可否分享一下划分好的数据集呢？谢谢

**Comment by Linfeng-Tang** [comment]
给一个邮箱 我看能否把我目前的数据集通过邮件附件的形式发你哈

**Comment by WinniePooh-XI** [comment]
> 给一个邮箱 我看能否把我目前的数据集通过邮件附件的形式发你哈

egrat11145@gmail.com

**Comment by WangCoCo** [comment]
同求这个划分好的数据集 方便的话也发我一份 感谢 邮箱 xtwang11@163.com
