### ISSUE TITLE
结果分析问题

### ISSUE THREAD

**Issue by Ghostuouorz** [Linfeng-Tang/SwinFusion#27]
请问有进行结果分析这部分的代码吗？测试并没有对结果进行评价指标的计算呀

**Comment by Linfeng-Tang** [comment]
评价指标可以参考：https://github.com/Linfeng-Tang/Image-Fusion
https://github.com/Linfeng-Tang/Evaluation-for-Image-Fusion
https://blog.csdn.net/fovever_/article/details/129332278
等
