### ISSUE TITLE
权重文件问题

### ISSUE THREAD

**Issue by 020607** [Linfeng-Tang/SwinFusion#34]
您好，请问为什么有三个权重文件，这三个权重文件分别是什么意思？

**Comment by Linfeng-Tang** [comment]
10000_E.pth
<https://github.com/Linfeng-Tang/SwinFusion/blob/master/Model/Medical_Fusion-PET-MRI/Medical_Fusion/models/10000_E.pth>
 和
10000_G.pth
<https://github.com/Linfeng-Tang/SwinFusion/blob/master/Model/Medical_Fusion-PET-MRI/Medical_Fusion/models/10000_G.pth>
 没啥区别 10000_optimizerG.pth
<https://github.com/Linfeng-Tang/SwinFusion/blob/master/Model/Medical_Fusion-PET-MRI/Medical_Fusion/models/10000_optimizerG.pth>
 保存的是优化器的参数。

aaa ***@***.***> 于2024年7月21日周日 21:40写道：

**Comment by 020607** [comment]
好的，感谢您的回答
