### ISSUE TITLE
通道数问题

### ISSUE THREAD

**Issue by biubiu116** [Linfeng-Tang/SwinFusion#35]
您好，我看您论文中说图像是将RGB转换为YCbCr中Y通道进行融合的（似乎是简单的转换为灰度图），但是模型以及数据集处理utils_image文件中的“imread_uint”也支持三个通道的输入，可以请教您是否支持三个通道RGB的图像处理呢？netG和netE有什么区别吗？

**Comment by AtomComm** [comment]
请问您解决这个问题了嘛

**Comment by AtomComm** [comment]
请问您解决这个问题了嘛

**Comment by Linfeng-Tang** [comment]
目前是Y通道进行融合的
